Repository wizeline/hacker-books, pull requests merged in 2020-08, with the labels that each got.

#1 Feat: nextjs setup
  .storybook/main.js
  .storybook/tsconfig.json
  components/button/index.stories.tsx
  next-env.d.ts
  package.json
  tsconfig.json
  yarn.lock
Labels: enhancement

#3 Add dev recommendations in README
  README.md
Labels: documentation

#2 Docs: Update base templates
  .github/CODEOWNERS
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: documentation

#4 Feat: Setting up Testing tools
  .babelrc
  .eslintrc.js
  commitlint.config.js
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/home_spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  jest.config.js
  next.config.js
  package.json
  pages/_app.tsx
  pages/api/__coverage__.js
  pages/api/hello.ts
  pages/index.test.js
  pages/index.tsx
  setupTests.js
  styles/styleMock.js
  yarn.lock
Labels: enhancement

#5 Fix(Config): Webpack config and Nextjs build
  containers/home.test.js
  containers/home.tsx
  next.config.js
  package.json
  pages/api/_health.ts
  pages/index.tsx
  yarn.lock
Labels: bug

#6 Feat(Config): Add tailwindcss configuration
  .storybook/manager.js
  .storybook/preview.js
  components/card/card.stories.tsx
  components/card/card.tsx
  package.json
  postcss.config.js
  styles/index.css
  tailwind.config.js
  yarn.lock
Labels: enhancement
